
@startuml syncronize_data

namespace GameClient {

class ServerRenderingProcPart
note top
レンダリングサーバーへ同期する情報を送って
返ってきた画像を表示する
endnote

class NamedPipeClient

class SyncronizeSerializeViewController
note bottom
同期するオブジェクトの
情報をシリアライズして
レンダリングサーバーへ
送るデータを作成する
endnote

class SyncronizeView
note bottom
レンダリングサーバーと
同期するオブジェクトを保持する
endnote

ServerRenderingProcPart *--> NamedPipeClient
ServerRenderingProcPart *--> SyncronizeSerializeViewController
SyncronizeSerializeViewController *--> SyncronizeView

}

namespace RenderingServer {

class SyncronizeRenderingProcPart
note top
ゲームクライアントから受け取った情報を同期し
描画した結果を送り返す
endnote

class NamedPipeServer

class SyncronizeDeserializeViewController
note bottom
ゲームクライアントから受け取った
情報をデシリアライズして
同期するオブジェクトに適用する
endnote

class SyncronizeView
note bottom
ゲームクライアントと
同期するオブジェクトを保持する
endnote

SyncronizeRenderingProcPart *--> NamedPipeServer
SyncronizeRenderingProcPart *--> SyncronizeDeserializeViewController
SyncronizeDeserializeViewController *--> SyncronizeView

}

GameClient.NamedPipeClient ..> RenderingServer.NamedPipeServer


@enduml