@startuml timer_class

class UniTask

interface ITimerCreator {
  UniTask Create()
}
note left
  対応する時間の処理を行う
  UniTask実装を生成する
endnote

class TimerCreator
class TestTimerCreator {
  EndTimer(int index)
}
note left of TestTimerCreator::EndTimer
  生成した順番を指定して
  タイマーを停止させる
  テスト用のメソッドを持つ
endnote

ITimerCreator <|.. TimerCreator
ITimerCreator <|.. TestTimerCreator
UniTask <-- ITimerCreator

@enduml