@startuml ui_class

class UnityEngile.MonoBehaviour
class UnityEngile.AnyUI
note bottom
  Buttonなどの
  Unityの組み込みUI
endnote

interface IAnyUIView
class AnyAccessorUIView
note bottom
  AnyUIと同じ種類のUIのアクセッサ
  AnyUIと同じGameObjectにアタッチして
  AnyUIの操作を行う
endnote

class AnyUIViewController
note bottom
  UIViewの操作を行う
endnote

UnityEngile.MonoBehaviour <|-- UnityEngile.AnyUI
UnityEngile.MonoBehaviour <|-- AnyAccessorUIView
IAnyUIView <|.. AnyAccessorUIView
UnityEngile.AnyUI <--* AnyAccessorUIView
IAnyUIView <--* AnyUIViewController

@enduml