@startuml ui_class

class UnityEngile.MonoBehaviour
class UnityEngile.AnyUI
note bottom
  Buttonなどの
  Unityの組み込みUI
endnote

interface IAnyUIView
class AnyUIViewAdapter
note bottom
  AnyUIをIAnyUIViewインターフェイスから
  操作するための機能

  Adapterデザインパターン
endnote

class AnyUIViewController
note bottom
  UIViewの操作を行う
endnote

UnityEngile.MonoBehaviour <|-- UnityEngile.AnyUI
UnityEngile.MonoBehaviour <|-- AnyUIViewAdapter
IAnyUIView <|.. AnyUIViewAdapter
UnityEngile.AnyUI <--* AnyUIViewAdapter
IAnyUIView <--* AnyUIViewController

@enduml