@startuml debug_rendering

class SyncronizeRenderingProcPart
class OffscreenRenderingViewController

class OffscreenRenderingView
note left
OffscreenRenderingViewControllerが
状態の管理を行う
endnote

class DebugRenderingUIControler
class DebugRenderingUI
note bottom
OffscreenRenderingViewが描画した
テクスチャを表示する
endnote

class RenderTexture

SyncronizeRenderingProcPart *--> OffscreenRenderingViewController
SyncronizeRenderingProcPart o--> DebugRenderingUIControler
OffscreenRenderingViewController *--> OffscreenRenderingView
DebugRenderingUIControler o--> OffscreenRenderingView
OffscreenRenderingView *--> RenderTexture
DebugRenderingUIControler *--> DebugRenderingUI
DebugRenderingUI ..> RenderTexture

@enduml